### ISSUE TITLE
More responsive site at mobile viewports

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#211]
Found in https://send.dev.mozaws.net/__version__ (8d00372):

```json
{
  "commit": "8d00372",
  "source": "https://github.com/mozilla/send/",
  "version": "0.1.2"
}

```

---

### Steps to reproduce:

1. Go to https://send.dev.mozaws.net/download/dc7e8417a6/#rZ1C9W-D9Fj2w9Hcy1BsRw
1. Resize to the browser to less than 500-600px wide.
1. Observe.

### Actual results:

<img width="958" alt="download_your_file" src="https://user-images.githubusercontent.com/557895/28296707-b2c4b4fc-6b1e-11e7-8faa-32f786e817b2.png">

Currently the site doesn't scale too well to narrower viewports.
In a few places in the CSS we have a fixed width of 630-640px, for example [/public/main.css:51](https://github.com/mozilla/send/blob/8d00372824faf0b4205128c8e414b20ada8e0096/public/main.css#L51):

```css
.description {
  font-size: 15px;
  line-height: 23px;
  width: 630px;
  text-align: center;
  margin: 0 auto 60px;
  color: #0C0C0D;
}
```

### Expected results:
Better handling for narrower/mobile viewports.
