### ISSUE TITLE
Check CSS for browser support

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#378]
Refs: [**stylelint-no-unsupported-browser-features**](https://github.com/ismay/stylelint-no-unsupported-browser-features) and [**browserslist**](https://github.com/ai/browserslist).

Although output is currently a bit verbose:

```sh
$ npm run lint:css

> firefox-send@1.0.2 lint:css /Users/pdehaan/dev/tmp/del/send-clean
> stylelint 'public/*.css'

public/main.css
  16:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
  19:3  ⚠  Unexpected browser feature "viewport-units" is only partially supported by IE 10,11,  plugin/no-unsupported-browser-features
           Edge 14,15
  26:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
  33:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
  39:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 110:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 158:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 173:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 203:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 253:3  ⚠  Unexpected browser feature "word-break" is only partially supported by Android        plugin/no-unsupported-browser-features
           Browser 4.4.3-4.4.4, QQ Browser 1.2
 291:3  ⚠  Unexpected browser feature "outline" is only partially supported by IE 10,11, Edge    plugin/no-unsupported-browser-features
           14
 318:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 327:3  ⚠  Unexpected browser feature "calc" is only partially supported by Android Browser      plugin/no-unsupported-browser-features
           4.4.3-4.4.4
 333:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 376:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 390:3  ⚠  Unexpected browser feature "user-select-none" is not supported by Baidu Browser 7.12  plugin/no-unsupported-browser-features
 391:3  ⚠  Unexpected browser feature "user-select-none" is not supported by Baidu Browser 7.12  plugin/no-unsupported-browser-features
 392:3  ⚠  Unexpected browser feature "user-select-none" is not supported by Baidu Browser 7.12  plugin/no-unsupported-browser-features
 407:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 431:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 443:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 535:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 553:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 584:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 630:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 668:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 684:3  ⚠  Unexpected browser feature "viewport-units" is only partially supported by IE 10,11,  plugin/no-unsupported-browser-features
           Edge 14,15
 685:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
 694:3  ⚠  Unexpected browser feature "viewport-units" is only partially supported by IE 10,11,  plugin/no-unsupported-browser-features
           Edge 14,15
 706:3  ⚠  Unexpected browser feature "flexbox" is only partially supported by IE 10,11          plugin/no-unsupported-browser-features
```

### .stylelintrc

```yaml
extends: stylelint-config-standard

plugins:
  - stylelint-no-unsupported-browser-features

rules:
  plugin/no-unsupported-browser-features:
    - true
    - severity: warning
      browsers:
      - '> 1%'
      - last 2 versions
      - firefox esr
      - not last 2 BlackBerry versions
      - not last 2 ExplorerMobile versions
      - not last 2 Opera versions
      - not last 2 OperaMini versions
      - not last 2 OperaMobile versions
      - not last 2 UCAndroid versions
      ignore: ['rem']

  color-hex-case: lower
  declaration-colon-newline-after: null
  selector-list-comma-newline-after: null
  value-list-comma-newline-after: null
```
