### ISSUE TITLE
Don't run tests+linting on Pontoon commits?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#501]
Not sure how much this this would improve things, but I was just looking at Circle-CI builds and notice that the Pontoon builds take 5-6 minutes each time a localization string changes. Not sure if we could tweak that by not doing some/all of the following:

```yml
dependencies:
  pre:
    - npm i -g get-firefox geckodriver nsp # 0:29s
    - get-firefox --platform linux --extract --target /home/ubuntu/send # 0:30s

test:
  override:
    # - ...
    - npm run lint # 0:08s
    - npm test # 0:07s
    - nsp check # 0:03s
```

Some _super_ rough calculations show it may cut the build by about 1:20, since the majority of the build timing seems to be in the docker steps.
