### ISSUE TITLE
Delete file from AWS when expired

### ISSUE THREAD

**Issue by lufficc** [mozilla/send#521]
When uploaded a file, no one downloads it.  After it expired, this record will delete from redis, **but not delete from AWS , right**?

**Comment by ehuggett** [comment]
I can't find it now but i remember seeing some discussion about this, i think it was suggesting something similar to https://aws.amazon.com/blogs/aws/amazon-s3-object-expiration/ was in use?

The expiry is rounded up to the "next midnight" and the link seems to suggest the only guarantee is that they will be deleted by the midnight after that one (as the rules are only applied once per day at an unspecified time).

**Comment by dannycoates** [comment]
@ehuggett is correct. We use S3 lifecycle expiration to delete the file from AWS.

Here's our exact portion of configuration for this bucket:
```yml
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 1
          Status: Enabled
```
